### ISSUE TITLE
No lyrics given for any arabic songs

### ISSUE THREAD

**Issue by CASPERg267** [zyrouge/node-genius-lyrics#30] opened 2022-07-11 17:42 UTC
when you try to get lyrics for any arabic song you get no results even if it exists on [genius.com](https://genius.com)

**Comment by zyrouge** [comment] 2022-07-22 11:51
Can you give an example with which I can reproduce the issue?

**Comment by CASPERg267** [comment] 2022-07-22 17:31
`let searches = await client.lyrics.songs.search(`Ahmed meky - atr el hayah`);
if (!searches) return `$No lyrics found`;
let firstSong = searches[0];
let lyrics = await firstSong.lyrics();
return lyrics;`

**Comment by zyrouge** [comment] 2022-07-23 15:31
> let searches = await client.lyrics.songs.search(`Ahmed meky - atr el hayah`); if (!searches) return `$No lyrics found`; let firstSong = searches[0]; let lyrics = await firstSong.lyrics(); return lyrics;

Tried it and it seems to be working just fine. Are you able to see the song in genius.com search? I'll close this since it seems to be working.

**Closed by zyrouge** 2022-07-23 15:31 UTC
Labels: bug, severity: medium
