### ISSUE TITLE
Error while trying to get lyrics

### ISSUE THREAD

**Issue by TaylorDuck72** [zyrouge/node-genius-lyrics#35] opened 2022-08-30 03:19 UTC
it threw a SyntaxError while trying to get lyrics from the API
```js
SyntaxError: Unexpected token < in JSON at position 0
```
![IMG_0862](https://user-images.githubusercontent.com/89784308/187341334-8c8fdec8-67f2-4b0e-87b7-47dfa0ad438a.jpeg)

Code:
```js
const lyricsClient = new lyricsFetch.Client()
      const lyricsInput = interaction.options.getString('query');

      try {
      const lyricsSearches = await lyricsClient.songs.search(lyricsInput);
      const lyricsResult = lyricsSearches[0];
      const audioLyrics = await lyricsResult.lyrics();
      } catch(e) 
```

**Comment by zyrouge** [comment] 2022-12-12 13:50
Could you provide reproducible steps and code for this?

**Comment by Tomato6966** [comment] 2022-12-19 10:33
This happens, due to cloudflare, when they respond with: 
https://milrato.com/codeshare/code/63a03d6f488d917ed402e653

**Comment by zyrouge** [comment] 2022-12-19 10:38
> This happens, due to cloudflare, when they respond with: https://milrato.com/codeshare/code/63a03d6f488d917ed402e653

There are no solutions for bypassing cloudflare. Only possible way is to use a proxy. Closing this since this cannot be fixed.

**Closed by zyrouge** 2022-12-19 10:38 UTC
Labels: bug, severity: medium
